// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$0 from "./loaders/availableIcons.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Contact/BecomeAPartner.tsx";
import * as $$$$$$2 from "./sections/Contact/ContactUs.tsx";
import * as $$$$$$3 from "./sections/Content/BannerVideo.tsx";
import * as $$$$$$4 from "./sections/Content/BigNumbers.tsx";
import * as $$$$$$5 from "./sections/Content/Hero.tsx";
import * as $$$$$$6 from "./sections/Content/HeroImage.tsx";
import * as $$$$$$7 from "./sections/Content/Info.tsx";
import * as $$$$$$8 from "./sections/Content/InfoCards.tsx";
import * as $$$$$$9 from "./sections/Content/InfoGrid.tsx";
import * as $$$$$$10 from "./sections/Content/Showcase.tsx";
import * as $$$$$$11 from "./sections/Content/Showpartners.tsx";
import * as $$$$$$12 from "./sections/Faq.tsx";
import * as $$$$$$13 from "./sections/Footer.tsx";
import * as $$$$$$14 from "./sections/Footer/SimpleFooter.tsx";
import * as $$$$$$15 from "./sections/Header.tsx";
import * as $$$$$$16 from "./sections/Header/HeaderMain.tsx";
import * as $$$$$$23 from "./sections/hero-1.tsx";
import * as $$$$$$24 from "./sections/hero-2.tsx";
import * as $$$$$$17 from "./sections/Hero.tsx";
import * as $$$$$$25 from "./sections/hero2.tsx";
import * as $$$$$$18 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$19 from "./sections/Logos.tsx";
import * as $$$$$$20 from "./sections/Testimonials.tsx";
import * as $$$$$$21 from "./sections/Theme/Fonts.tsx";
import * as $$$$$$22 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$0,
  },
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Contact/BecomeAPartner.tsx": $$$$$$1,
    "site/sections/Contact/ContactUs.tsx": $$$$$$2,
    "site/sections/Content/BannerVideo.tsx": $$$$$$3,
    "site/sections/Content/BigNumbers.tsx": $$$$$$4,
    "site/sections/Content/Hero.tsx": $$$$$$5,
    "site/sections/Content/HeroImage.tsx": $$$$$$6,
    "site/sections/Content/Info.tsx": $$$$$$7,
    "site/sections/Content/InfoCards.tsx": $$$$$$8,
    "site/sections/Content/InfoGrid.tsx": $$$$$$9,
    "site/sections/Content/Showcase.tsx": $$$$$$10,
    "site/sections/Content/Showpartners.tsx": $$$$$$11,
    "site/sections/Faq.tsx": $$$$$$12,
    "site/sections/Footer.tsx": $$$$$$13,
    "site/sections/Footer/SimpleFooter.tsx": $$$$$$14,
    "site/sections/Header.tsx": $$$$$$15,
    "site/sections/Header/HeaderMain.tsx": $$$$$$16,
    "site/sections/hero-1.tsx": $$$$$$23,
    "site/sections/hero-2.tsx": $$$$$$24,
    "site/sections/Hero.tsx": $$$$$$17,
    "site/sections/hero2.tsx": $$$$$$25,
    "site/sections/ImageWithParagraph.tsx": $$$$$$18,
    "site/sections/Logos.tsx": $$$$$$19,
    "site/sections/Testimonials.tsx": $$$$$$20,
    "site/sections/Theme/Fonts.tsx": $$$$$$21,
    "site/sections/Theme/Theme.tsx": $$$$$$22,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
